name: 'my_dbt_project'
version: '1.0'
profile: 'default'

model-paths: ["C:/Users/henrique.soares/Desktop/DGU/models"]
seed-paths: ["C:/Users/henrique.soares/Desktop/DGU/seeds"]
models:
  my_dbt_project:
    newmodel:
      +materialized: view  # Especifica que o modelo será materializado como 'view'
