name: 'my_dbt_project'
version: '1.0'
profile: 'default'

# Caminhos para os modelos
model-paths: ["C:/Users/henrique.soares/Desktop/DataGlowUp/models"]
seed-paths: ["C:/Users/henrique.soares/Desktop/DataGlowUp/seeds"]

# Se você estiver utilizando configurações específicas para modelos, pode manter algo assim:
models:
  my_dbt_project:
    materialized: table
