default:
  outputs:
    dev:
      dbname: mydatabase
      host: localhost
      pass: mypassword
      port: 5432
      schema: public
      threads: 3
      type: postgres
      user: myuser
  target: dev
